url: "https://thisaru.me"
title: "Thisaru Guruge"
description: "Official Website of Thisaru Guruge"
email: thisaru.guruge@gmail.com

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: ''

plugins:
  - jekyll-sitemap
