url: "https://www.thisaru.me"
title: "Thisaru Guruge"
description: "Official Website of Thisaru Guruge"
email: thisaru.guruge@gmail.com
keywords: "thisaru, guruge, thisaru guruge, graphql, ballerina, Sinhala, Sri Lanka, සිංහල විචාර"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: ''

plugins:
  - jekyll-sitemap
